jobs:
  build:
    runs-on: ubuntu-latest
    container: coqorg/coq:8.20
    steps:
      - name: Install git
        run: |
          apt-get update
          apt-get install -y git
          
      - uses: actions/checkout@v4

      - name: Build
        run: |
          chmod -R 777 .
          coq_makefile -f _CoqProject -o CoqMakefile
          make -f CoqMakefile all